# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
    - main
    - release/*
jobs:
  backend-services:
  
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: |
        mvn -DskipTests -B package --file Backend/AccountService/pom.xml
        mvn -DskipTests -B package --file Backend/PrescriptionService/pom.xml
        mvn -DskipTests -B package --file Backend/AppointmentBookingService/pom.xml
        mvn -DskipTests -B package --file Backend/ChatService/pom.xml
        mvn -DskipTests -B package --file Backend/MessageService/pom.xml
      
